name: deploy gh-pages
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  build:
    name: Build and deploy gh-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          pnpm install
      - name: Run build
        run: |
          pnpm run build
      - name: Deploy with gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true